Profile settings
FullstackAcademy/2007-new-clear-reacto pull request #92
Opened 2020-11-01 19:29 UTC by antonpreku

Log out and edit profile

2020-11-01 22:09 UTC, jamato25 commented
This looks great.  Only two issues that I can see:
1) I hit an error when I tries to log out that says: react_devtools_backend.js:2450 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Sanduich (created by ConnectFunction)
    in ConnectFunction (created by NavBar)

2) When I sign in and click the settings button in the hamburger, it does not redirect me to the settings page until I click it one or two more times.  Not sure what this issue is.

2020-11-02 03:57 UTC, jpcook72 requested changes
The adds look good but I think log-out bug should be fixed before we merge in... I think it should be a quick fix (see comment)

2020-11-02 03:57 UTC, jpcook72 commented on server/routes/logout.js
> -    await session.destroy()
Was there a reason you changed where session.destroy was? I think this is why it is giving a bug. You can't clear the cookie with the session id after you destroy the session... session.destroy() needs to happen after the cookie is cleared

2020-11-02 04:22 UTC, jpcook72 approved these changes

2020-11-02 04:22 UTC, merged